### ISSUE TITLE
ESP32-S3 Adafruit Feather: golioth_basics shell hangs when host machine has not opened the serial port

### ISSUE THREAD

**Issue by ncmiller** [golioth/golioth-firmware-sdk#48]
### Golioth Firmware SDK Commit Hash

aef2d9d606210ce5c8fd85b608c430b456316203

### Platform/OS

ESP-IDF v4.4.2

### Hardware Target

ESP32-S3 Adafruit Feather

### What host OS are you using?

Ubuntu 22.04.01 LTS

### Current Behavior

See the bug filed upstream in esp-idf for a description: https://github.com/espressif/esp-idf/issues/10324

This issue is just for tracking the upstream issue.

**Comment by beriberikix** [comment]
Looks like the fix was merged in ESP-IDF `main`? https://github.com/espressif/esp-idf/issues/10324#issuecomment-1444675565

**Comment by ncmiller** [comment]
> Looks like the fix was merged in ESP-IDF `main`? [espressif/esp-idf#10324 (comment)](https://github.com/espressif/esp-idf/issues/10324#issuecomment-1444675565)

Yes, it's in `master` right now. 

This repo is typically based on stable IDF releases, and since the latest (as of now, https://github.com/espressif/esp-idf/releases/tag/v5.0.1) doesn't have commit `720b8d9`, we should probably wait until there's a stable release (probably the next one, so should be soon).

**Comment by sam-golioth** [comment]
We are now using ESP-IDF version 5.1.1 which includes the upstream fix.
