### ISSUE TITLE
Adding Golioth to PlatformIO ESP-IDF/Arduino Project

### ISSUE THREAD

**Issue by atfox98** [golioth/golioth-firmware-sdk#524]
### Golioth Firmware SDK Commit Hash

bb11ba9bd2388f30215dd345b3061a946f69003c

### Platform/OS

PlatformIO (framework = arduino, espidf). Appears to be ESP-IDF 4.4.6

### Hardware Target

ESP32

### What host OS are you using?

Windows 10

### Current Behavior

Problems including golioth-firmware-sdk into PlatformIO project. Golioth settings show up in menuconfig but compilation fails. See repo @ https://github.com/atfox98/golioth-pio.

### Expected Behavior

Successful build

### Steps To Reproduce

Clone minimal example repository @ https://github.com/atfox98/golioth-pio

### Logs, console output, or any kind of debug information

```shell
Compiling .pio\build\esp32dev\components\golioth-firmware-sdk\src\zcbor_utils.o
*** [.pio\build\esp32dev\.pio\build\esp32dev\isrgrootx1.der.o] Source `.pio\build\esp32dev\isrgrootx1.der.S' not found, needed by target `.pio\build\esp32dev\.pio\build\esp32dev\isrgrootx1.der.o'.
```

**Comment by MarkoPura** [comment]
Hey @atfox98, great find, glad you can now build your application.

**Comment by MarkoPura** [comment]
I overlooked the fact that PlatformIO applications are written in C++. We do have a [minimal example](https://github.com/golioth/golioth-firmware-sdk/tree/main/examples/esp_idf/cpp) for ESP-IDF to verify that a C++ application can be used with Golioth. It also uses the `extern "C"` around the includes as your application. We'll take a look at adding changes to header files to address the issue.

**Comment by MarkoPura** [comment]
Hey @atfox98, we have added the extern “C” block to header files to avoid linking problems when building C++ applications. You can check out the changes in [this commit](https://github.com/golioth/golioth-firmware-sdk/commit/ee39e9bda8e9359333e83aba9a4bbdda4299cd73).
